language: java
jdk:
  - oraclejdk8

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: mvn clean verify

notifications:
  email: false

services:
  - postgresql

env:
  - DB_URL=jdbc:postgresql://localhost:5432/travis_ci_test DB_USERNAME=postgres