server:
  port: 8081

spring:
  profiles:
    active: dev, security, pay-salary
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

---
spring:
  profiles: dev



---
spring:
  profiles: security
security:
  basic:
    enabled: true

---
spring:
  profiles: no-security
security:
  basic:
    enabled: false