server:
  port: 8083

spring:
  profiles:
    active: dev, enable-scheduling
  cloud:
    stream:
      bindings:

       transfer_money_channel:
        destination: transfer_money.exchange
        contentType: application/json