server:
  port: 8083

spring:
  profiles:
    active: scheduling

---
spring:
  profiles: cloud
  cloud:
    stream:
      bindings:
       transfer_money_channel:
        destination: transfer_money.exchange
        contentType: application/json