server:
  port: 8081

spring:
  profiles:
    active: dev, cloud, security
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.hbm2ddl.auto: update
      hibernate.enable_lazy_load_no_trans: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e-wallet?useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8
    username: postgres
    password: root
---
spring:
  profiles: cloud
  cloud:
    stream:
      bindings:
       transfer_money_channel:
        destination: transfer_money.exchange
        group: e-wallet
       user_created_channel:
        destination: user_created.exchange
        group: e-wallet
---
spring:
  profiles: security
security:
  basic:
    enabled: true

---
spring:
  profiles: no-security
security:
  basic:
    enabled: false